pipeline{
    //agent any
    agent {
        docker { image 'maven:3.9.2-openjdk-11' }
        //docker { image 'node:16-alpine' }
    }
    stages{
        stage('build')
        {
            steps{
                sh 'mvn clean package'
            }
            post{
                success{
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        
    }
}